### ISSUE TITLE
Lock files

### ISSUE THREAD

**Issue by mrazauskas** [everweij/typescript-result#12]
Is it intentional to have both `package-lock.json` and `pnpm-lock.yaml` in this repo? Seems like `npm` is used as package manager. Hence `pnpm-lock.yaml` shouldn’t be around. Or? It might be I missed something, of course (;

**Comment by everweij** [comment]
Good catch! I removed the wrong one -> `package-lock.json`, so I'm actually using `pnpm` :)
Tnx!

**Comment by everweij** [comment]
Ow, snap, it was the other way around :)
So, you were right, `npm` is the correct package manager. Fixed it.
